# Generated by Django 4.2.2 on 2023-07-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='file/%Y-%m-%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
