# Generated by Django 4.2.2 on 2023-07-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='cover',
        ),
    ]
