# Generated by Django 5.1.6 on 2025-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_file_options_remove_file_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='ile/')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Пользователь сайта',
                'verbose_name_plural': 'Пользователи сайта',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Расшифровка файла'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AddField(
            model_name='file',
            name='city',
            field=models.CharField(default='-', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='file',
            name='fed_o',
            field=models.CharField(default='-', verbose_name='Федеральный округ'),
        ),
        migrations.AddField(
            model_name='file',
            name='his',
            field=models.CharField(default='-', verbose_name='Основание или первое упоминание'),
        ),
        migrations.AddField(
            model_name='file',
            name='his_name',
            field=models.CharField(default='-', verbose_name='Прежние названия'),
        ),
        migrations.AddField(
            model_name='file',
            name='hum',
            field=models.CharField(default='-', verbose_name='Население'),
        ),
        migrations.AddField(
            model_name='file',
            name='num',
            field=models.CharField(default='-', verbose_name='№'),
        ),
        migrations.AddField(
            model_name='file',
            name='reg',
            field=models.CharField(default='-', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default='-', verbose_name='Статус города'),
        ),
    ]
